### ISSUE TITLE
Simply Jetpacks recipies out-of-date / missing

### ISSUE THREAD

**Issue by tweak42** [andrewminer/crafting-guide-data#5]
Simply Jetpacks recipes were changed in 1.5.0 and need updating.  Additionally the Simply Jetpacks for enderio recipes appear to be missing.

Changelog here:
https://github.com/Tonius/SimplyJetpacks/blob/22f6e9e97534dc17ac678a05ec8c90dc0523c710/VersionHistory.md

**Comment by andrewminer** [comment]
Moved to [Trello](https://trello.com/c/V83TKTAD/185-update-simply-jetpacks-for-v1-5-0).
